spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmmaZhou_timeManagement?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    dirver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath*:mapper/**/**.xml

server:
  port: 8888
  tomcat.uri-encoding: UTF-8

#    url: jdbc:mysql://172.19.5.12:3306/zmhtest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true

